name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project structure
        run: tree

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate k8s configs
        run: |
          kubectl apply --dry-run=client --validate=false -f k8s/
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes manifests
        run: |
          kubeconform -summary k8s/*.yaml
